baseURL: https://www.aman-applied-statistics.netlify.app/
languageCode: en-us
title: Aman
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Learn More
    subtitle: |-
      WELCOME TO MY PORTFOLIO WEBSITE - LEARN MORE ABOUT ME AND CHECK OUT SOME ANALYSIS I HAVE CONDUCTED USING R.
  
    title: Hey, my name is Aman
  blog: {}
  contact:
    address:
      - city: Maidenhead, SL6 3EH
        country: United Kingdom
        street: Cox Green Road
        title: Address
    buttonClear: Start Again
    buttonSend: Say Hello
    email:
      - email: amanakshay@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (0791) 5878-953
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/AmanSharmaGitHub
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/amanakshaysharma
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Portfolio
    title: Aman
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Page 1
        url: blogs/pageone
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Page 2
        url: blogs/pagetwo
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Page 3
        url: blogs/pagethree
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Page 4
        url: blogs/pagefour
        - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Page 3
        url: blogs/pagefive
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Page 4
        url: blogs/pagesix

  two:
    buttonText: Check it out
    enable: yes
    subtitle: "Welcome to my portfolio website. My name is Aman, I am British and from a 2nd generation Indian immigrant family. We are Hindu Punjabis from North India.
    I have lived in the UK all my life. I studied at UCL for my undergraduate and the next challenge is the MAM at LBS!
    I have included some data analysis conducted using R, please take a look!"
    title: Welcome!
    url: blogs
